### ISSUE TITLE
Can't install xcrysden

### ISSUE THREAD

**Issue by boyoungzheng** [agiliopadua/homebrew-extras#2]
Homebrew does not have formula "x11". By the way, I have Xquatz installed. Are there any options to use "my" available xquartz? Thank you.

==> Installing xcrysden from agiliopadua/extras
Error: No available formula with the name "x11" (dependency of agiliopadua/extras/xcrysden)
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
This similarly named formula was found:
x11vnc
To install it, run:
  brew install x11vnc
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Homebrew 1.7.0
Homebrew/homebrew-core (git revision b47f6e; last commit 2018-07-19)
MacOS 10.13.5
XQuartz 2.7.11 (xorg-server 1.18.4)

**Comment by agiliopadua** [comment]
Hello,

This formula is broken because of some issue in the tcl/tk needed by xcrysden, which is an outdated version.
I’ll try to fix the x11 issue but that’s not the main problem…

Regards,
Agilio

**Comment by specter119** [comment]
@boyoungzheng, I agree with @agiliopadua x11 is not the main problem, I have tried tcl/tk 8.5, 8.6, 8.7 and mac os default, none of them works. you can view all my attempts at <https://gist.github.com/specter119/4f630e538d39edcf67ec742f78c23aab> .

**Comment by boyoungzheng** [comment]
The Macport can successfully build Xcrysden. I have absolutely no idea how it works. Maybe you code genius can look into it and do the same trick in homebrew? I prefer installing through homebrew :-)

**Comment by specter119** [comment]
@boyoungzheng I know [MacPort](https://github.com/macports/macports-ports/blob/master/science/xcrysden/Portfile) and [Fink](https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/sci/xcrysden.info) can build it. But their codes haven't change for quite a long time.

Thanks to @agiliopadua, I believe that he has made all the most necessary modifications (you can compare the modification in MacPort and Fink I provide). Also his codes could also help you build xcrysden in the near past.

But the **New** issue is:

```
5156 Segmentation fault: 11  ${XCRYSDEN_XCRYS_DIR}/xcrys ${XCRYSDEN_TOPDIR}/Tcl/xcInit.tcl $USE -- $XCRYSDEN_TOPDIR $XCRYSDEN_SCRATCH "$@" > /dev/null
```

when xcrysden launches (you can successfully build xcrysden with tcl/tk 8.5/8.6/8.7/system with the code in  [my gist](https://gist.github.com/specter119/4f630e538d39edcf67ec742f78c23aab)).

This issue is more related to homebrew tcl/tk or even MacOS itself I guess, and few useful message in xcrysden mail list mentioned this.

I also eager to use xcrysden on Mac natively, but I finally turn to linux instead. I think you should consider MacPort, Fink, Linux or even WSL on windows as an alternative way.

I know nothing about tcl/tk, so that I'm not able to fix this at all. If you find any one can fix this, I am happy to merge it to [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science).

**Comment by Tomoki9684** [comment]
Thanks to @agiliopadua patch. I can successfully build XCrysden from source package. Although there is the error( http://www.democritos.it/pipermail/xcrysden/2015-October/001750.html ), we can solve its error( http://www.democritos.it/pipermail/xcrysden/2015-October/001754.html) from xcrysden_root/F/gengeom.f.
Before compiling, I performed `export PATH="/usr/local/bin:$PATH"`,`brew install tcl-tk --with-threads --with-x11` and `brew link tcl-tk --overwrite --force`.
I hope to become clue of problem solving.

**Comment by specter119** [comment]
@Tomoki9684 `tcl-tk` no longer have `--with-threads` and `--with-x11` options

**Comment by Tomoki9684** [comment]
@specter119  I'm sorry that I forget to tell about changing the formula. we can download this address (https://www.dropbox.com/s/tq2dsvtclsmt0ec/tcl-tk.rb?dl=0) with `--with-threads` and `--with-x11` options. Please, overwrite homebrew/core formula. However, I cannot open the bxsf format (ex. Fermi Surface) because of `Segmentation fault: 11`.

**Comment by specter119** [comment]
Dear all, according to @Tomoki9684's opinion, I have add `--with-x11` to `tcl-tk`, and add `xcrysden` to [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science). you can see:

[add with-x11 option for tcl-tk](https://github.com/Homebrew/homebrew-core/pull/30756)
[add xcrysden](https://github.com/brewsci/homebrew-science/pull/193)

you can wait for the 2 prs merging, or build them by modify your local homebrew.

---

update:

because homebrew-science has been archive and is not maintained.

you can install xcrysden by my fork of [homebrew-science](https://github.com/specter119/homebrew-science)

by the way, bxsf related functions work well.
